MOTOR_CMD_RATE = 20             # Max number of motor commands per second
L_ROPE_0 = 109.5                 # Length of left rope in cm when pen is at 0,0 (top left)
R_ROPE_0 = 129.0                # same for right rope
ROPE_ATTACHMENT_WIDTH = 90.0    # space between the two attachment points of the plotter.In my case: door width. In cm.
PULLEY_DIAMETER = 4.4
KP=1.5
TI=1
TD=0.05
MAX_SPEED=700
