MOTOR_CMD_RATE = 20             # Max number of motor commands per second
L_ROPE_0 = 96.0                 # Length of left rope in cm when pen is at 0,0 (top left)
R_ROPE_0 = 122.5                # same for right rope
ROPE_ATTACHMENT_WIDTH = 90.0    # space between the two attachment points of the plotter.In my case: door width. In cm.
PULLEY_DIAMETER = 4.4
KP=1
TI=0.3
TD=0.02
MAXPWR=100
